import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { ROUTES } from '@/constants/routes';

const CONTACT_EMAIL = 'chaurasiashubh195@gmail.com';

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

function Section({ title, children }: SectionProps): JSX.Element {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-lg font-semibold text-text-primary">{title}</h2>
      <div className="flex flex-col gap-2 text-sm leading-relaxed text-text-secondary">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage(): JSX.Element {
  return (
    <div className="min-h-screen bg-bg pb-24 pt-28">
      <div className="mx-auto max-w-3xl px-6">
        {/* Back */}
        <Link
          to={ROUTES.HOME}
          className="inline-flex items-center gap-1.5 text-sm text-text-muted transition-colors hover:text-text-primary"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to home
        </Link>

        {/* Title */}
        <div className="mb-12 mt-8 border-b border-border/60 pb-8">
          <h1 className="text-3xl font-bold tracking-tight text-text-primary">Terms of Service</h1>
          <p className="mt-2 text-sm text-text-muted">Last updated: July 2026</p>
        </div>

        {/* Sections */}
        <div className="flex flex-col gap-10">

          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using ScamShield AI (the "Service"), you agree to be bound by these
              Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the
              Service.
            </p>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the Service
              after changes are published constitutes your acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="2. Service Description">
            <p>
              ScamShield AI is a cybersecurity intelligence platform that helps users identify
              potential scams, phishing attempts, and malicious content across multiple vectors —
              including URLs, emails, SMS messages, QR codes, and images.
            </p>
            <p>
              The Service uses a combination of rule-based detection, heuristic analysis, and
              AI-powered explanation to surface threat intelligence. The Service is provided on an
              "as-is" and "as-available" basis.
            </p>
          </Section>

          <Section title="3. AI Disclaimer">
            <p>
              Scan results and AI-generated explanations provided by ScamShield AI are for
              informational purposes only. They do not constitute professional cybersecurity advice
              and should not be relied upon as the sole basis for security decisions.
            </p>
            <p>
              Our detection engine may produce false positives (flagging legitimate content as risky)
              or false negatives (missing genuinely malicious content). Always exercise independent
              judgement when evaluating potential threats.
            </p>
            <p>
              AI explanations are generated by Groq's large language models and are subject to the
              limitations and potential inaccuracies inherent in generative AI systems.
            </p>
          </Section>

          <Section title="4. User Responsibilities">
            <p>By using the Service, you agree to:</p>
            <ul className="ml-4 flex flex-col gap-1.5">
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary/60" />
                <span>Use the Service only for lawful purposes and legitimate security analysis.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary/60" />
                <span>Keep your account credentials secure and not share them with others.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary/60" />
                <span>Provide accurate information when creating your account.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary/60" />
                <span>Accept responsibility for all activity that occurs under your account.</span>
              </li>
            </ul>
          </Section>

          <Section title="5. Prohibited Use">
            <p>You may not use the Service to:</p>
            <ul className="ml-4 flex flex-col gap-1.5">
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-danger/60" />
                <span>Perform automated mass scanning or abuse our API endpoints.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-danger/60" />
                <span>Attempt to reverse-engineer, decompile, or extract the detection engine logic.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-danger/60" />
                <span>Submit content designed to compromise or overload our systems.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-danger/60" />
                <span>Use the Service for illegal activities or to facilitate harm to others.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-danger/60" />
                <span>Impersonate any person or entity or misrepresent your affiliation.</span>
              </li>
            </ul>
            <p>
              Violation of these prohibitions may result in immediate termination of your account
              without notice.
            </p>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              ScamShield AI, including its name, design, detection logic, and codebase, is the
              intellectual property of Shubh Chaurasia. All rights are reserved.
            </p>
            <p>
              You are granted a limited, non-exclusive, non-transferable licence to access and use
              the Service for its intended purpose. This licence does not grant you any right to
              reproduce, redistribute, or create derivative works from the Service.
            </p>
            <p>
              The source code is available on GitHub under the terms specified in the repository's
              licence file.
            </p>
          </Section>

          <Section title="7. Limitation of Liability">
            <p>
              To the fullest extent permitted by applicable law, ScamShield AI and its creator
              shall not be liable for any indirect, incidental, special, consequential, or punitive
              damages arising from or related to your use of, or inability to use, the Service.
            </p>
            <p>
              This includes but is not limited to damages arising from reliance on scan results,
              false positives or negatives in threat detection, or any security incident that
              occurs despite using the Service.
            </p>
            <p>
              The Service is provided free of charge. In jurisdictions that do not allow the
              exclusion of certain warranties or limitation of liability, our liability is limited
              to the fullest extent permitted by law.
            </p>
          </Section>

          <Section title="8. Contact">
            <p>
              For questions, complaints, or notices relating to these Terms, please contact us at:
            </p>
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="inline-flex items-center gap-1.5 text-primary hover:underline"
            >
              {CONTACT_EMAIL}
            </a>
          </Section>

        </div>

        {/* Footer note */}
        <div className="mt-16 border-t border-border/60 pt-6">
          <p className="text-xs text-text-muted">
            These Terms constitute the entire agreement between you and ScamShield AI regarding
            your use of the Service and supersede any prior agreements.
          </p>
          <Link
            to={ROUTES.HOME}
            className="mt-4 inline-flex items-center gap-1.5 text-sm text-text-muted transition-colors hover:text-text-primary"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
